page/urls.py
from django.urls import path
from django.utils.translation import ugettext_lazy as _

from page import views

urlpatterns = [
    path("", views.HomePage.as_view(), name="home"),
    path(_("about/"), views.AboutPage.as_view(), name="about"),
    path(_("about-doctor/"), views.AboutDoctorPage.as_view(), name="about_doctor"),
    path(_("why-us/"), views.WhyUsPage.as_view(), name="why_us"),
    path(_("success-rates/"), views.SuccessRatesPage.as_view(), name="success_rates"),
    path(_("how-it-works/"), views.HowItWorksPage.as_view(), name="how_it_works"),
    path(_("services/"), views.ServicesListView.as_view(), name="services"),
    path(_("services/<slug>/"), views.ServicesDetailView.as_view(), name="services_detail"),
    path(_("journey/"), views.JourneyPage.as_view(), name="journey"),
    path(_("experience/"), views.ExperiencePage.as_view(), name="experience"),
    path(_("blog/"), views.BlogListView.as_view(), name="blog_list"),
    path(_("blog/<slug>/"), views.BlogDetailView.as_view(), name="blog_detail"),
    path(_("contact/"), views.ContactPage.as_view(), name="contact"),
    path(_("gdpr/"), views.GDPRPage.as_view(), name="gdpr"),
    path(_("privacy/"), views.PrivacyPage.as_view(), name="privacy"),
    path(
        "handle-contact-form/",
        views.HomeContactFormView.as_view(),
        name="handle_home_contact_form",
    ),
    path(
        "handle-first-step-form/",
        views.FirstStepFormView.as_view(),
        name="handle_first_step_form",
    ),
]

page/models/blogs.py
from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor.fields import RichTextField
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import ugettext as _tr
from parler.models import TranslatableModel, TranslatedFields
from parler.utils.context import switch_language

from page.models import seo_translations, SEOStarterModel
from page.models.faqs import faqs_fields
from utils.models import TimestampStarterModel, BannerStarterModel


class BlogsPageSeo(TranslatableModel, SEOStarterModel, BannerStarterModel):
    translations = TranslatedFields(
        **BannerStarterModel.translations, **seo_translations
    )

    class Meta:
        verbose_name = _("Blogs Page SEO")
        verbose_name_plural = _("Blogs Page SEO")

    def __str__(self):
        return _tr("Blogs Page Seo")


class BlogCategory(TranslatableModel, TimestampStarterModel):
    translations = TranslatedFields(
        title=models.CharField(_("Title"), max_length=100),
        slug=models.SlugField(_("Slug"), max_length=100),
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("Blog Category")
        verbose_name_plural = _("Blog Categories")

    def get_absolute_url(self):
        with switch_language(self):
            return "{}?category={}".format(reverse(f"blog_list"), self.slug)

    @property
    def blog_count(self):
        return self.blog_set.count()


class Blog(
    TranslatableModel, SEOStarterModel, TimestampStarterModel, BannerStarterModel
):
    translations = TranslatedFields(
        title=models.CharField(_("Title"), max_length=200),
        slug=models.SlugField(_("Slug"), max_length=200),
        description=RichTextField(verbose_name=_("Description"), blank=True, null=True),
        content=RichTextUploadingField(_("Content"), blank=True, null=True),
        **BannerStarterModel.translations,
        **seo_translations,
        **faqs_fields,
    )
    category = models.ForeignKey(
        BlogCategory,
        verbose_name=_("Category"),
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    image = models.ImageField(_("Blog Image"), upload_to="blogs", blank=True, null=True)
    author_image = models.ImageField(
        _("Author Image"), upload_to="blogs/authors", blank=True, null=True
    )
    author = models.CharField(
        verbose_name=_("Author"), max_length=100, blank=True, null=True
    )
    view_count = models.IntegerField(default=0, verbose_name=_("View Count"))

    class Meta:
        verbose_name = _("Blog")
        verbose_name_plural = _("Blogs")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        with switch_language(self):
            return reverse(f"blog_detail", args=(self.slug,))

    def increase_view_count(self):
        self.view_count += 1
        self.save()

    def save(self, *args, **kwargs):
        if not self.banner_title:
            self.banner_title = self.title
        if not self.banner_description:
            self.banner_description = self.description
        if not self.seo_title:
            self.seo_title = self.title
        super().save(*args, **kwargs)

page/models/contact.py
from django.utils.translation import ugettext as _tr
from django.utils.translation import ugettext_lazy as _
from parler.models import TranslatableModel, TranslatedFields

from page.models import seo_translations, SEOStarterModel
from utils.models import BannerStarterModel


class ContactPageSeo(TranslatableModel, SEOStarterModel, BannerStarterModel):
    translations = TranslatedFields(
        **BannerStarterModel.translations,
        **seo_translations
    )

    class Meta:
        verbose_name = _("Contact Page SEO")
        verbose_name_plural = _("Contact Page SEO")

    def __str__(self):
        return _tr("Contact Page Seo")

page/models/experience.py
from django.db import models
from django.utils.translation import ugettext as _tr
from django.utils.translation import ugettext_lazy as _
from parler.models import TranslatableModel, TranslatedFields

from page.models import seo_translations, SEOStarterModel
from utils.models import BannerStarterModel


class ExperiencePageSeo(TranslatableModel, SEOStarterModel, BannerStarterModel):
    translations = TranslatedFields(
        **BannerStarterModel.translations,
        **seo_translations,
    )

    class Meta:
        verbose_name = _("Experience Page SEO")
        verbose_name_plural = _("Experience Page SEO")

    def __str__(self):
        return _tr("Experience Page SEO")


class ExperienceCategory(TranslatableModel):
    translations = TranslatedFields(
        title=models.CharField(verbose_name=_("Title"), max_length=100),
        slug=models.SlugField(max_length=100, verbose_name=_("Slug"))
    )

    class Meta:
        verbose_name = _("Experience Category")
        verbose_name_plural = _("Experience Categories")

    def __str__(self):
        return self.title


class ExperienceItem(models.Model):
    title = models.CharField(verbose_name=_("Title"), max_length=100),
    image = models.ImageField(_("Image"), upload_to="experience", blank=True, null=True)
    category = models.ForeignKey(ExperienceCategory, verbose_name=_("category"), blank=True, null=True,
                                 on_delete=models.SET_NULL)
    is_clinic = models.BooleanField(default=False, verbose_name=_("In Jineart Clinic?"))
    is_lab = models.BooleanField(default=False, verbose_name=_("In Jineart Lab?"))

    class Meta:
        verbose_name = _("Experience Item")
        verbose_name_plural = _("Experience Items")

    def __str__(self):
        return str(self.pk)

page/models/faqs.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.translation import ugettext_lazy as _
from parler.models import TranslatableModel, TranslatedFields


faqs_fields = dict(
    faq_subtitle=models.CharField(
        _("FAQ Subtitle"), max_length=250, blank=True, null=True
    ),
    faq_title=models.CharField(_("FAQ Title"), max_length=250, blank=True, null=True),
    faq_description=models.TextField(_("FAQ Description"), blank=True, null=True),
)


class FAQ(TranslatableModel):
    translations = TranslatedFields(
        question=models.CharField(max_length=250, verbose_name=_("Question")),
        answer=RichTextField(verbose_name=_("Answer")),
    )
    service = models.ForeignKey(
        "page.ServiceItem",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name=_("Service"),
    )
    blog = models.ForeignKey(
        "page.Blog",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name=_("Blog"),
    )
    about = models.ForeignKey(
        "page.AboutPageSeo",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name=_("About Page"),
    )
    about_doctor = models.ForeignKey(
        "page.AboutDoctorPageSeo",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name=_("Cengiz Sagiroglu Page"),
    )
    about_clinic = models.ForeignKey(
        "page.JineartClinicPageSeo",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name=_("Jineart Clinic Page"),
    )
    about_lab = models.ForeignKey(
        "page.JineartLabPageSeo",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name=_("Jineart Lab Page"),
    )
    howitworks = models.ForeignKey(
        "page.HowItWorksPageSeo",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name=_("How It Works Page"),
    )

    class Meta:
        verbose_name = _("Frequently Asked Question")
        verbose_name_plural = _("Frequently Asked Questions")

    def __str__(self):
        return self.question

page/models/gdpr.py
from django.utils.translation import ugettext_lazy as _
from parler.models import TranslatableModel, TranslatedFields
from ckeditor_uploader.fields import RichTextUploadingField

from page.models import seo_translations, SEOStarterModel
from utils.models import BannerStarterModel


class GDPRPageSeo(TranslatableModel, SEOStarterModel, BannerStarterModel):
    translations = TranslatedFields(
        content=RichTextUploadingField(_("Content"), blank=True, null=True),
        **BannerStarterModel.translations,
        **seo_translations
    )

    class Meta:
        verbose_name = _("GDPR Page SEO")
        verbose_name_plural = _("GDPR Page SEO")


class PrivacyPageSeo(TranslatableModel, SEOStarterModel, BannerStarterModel):
    translations = TranslatedFields(
        content=RichTextUploadingField(_("Content"), blank=True, null=True),
        **BannerStarterModel.translations,
        **seo_translations
    )

    class Meta:
        verbose_name = _("Privacy Page SEO")
        verbose_name_plural = _("Privacy Page SEO")

page/models/home.py
from django.db import models
from django.utils.translation import gettext as _tr
from django.utils.translation import ugettext_lazy as _
from parler.models import TranslatableModel, TranslatedFields
from ckeditor.fields import RichTextField

from page.models import seo_translations, SEOStarterModel


class HomePageSeo(TranslatableModel, SEOStarterModel):
    translations = TranslatedFields(
        **seo_translations,
    )

    def __str__(self):
        return _tr("Home SEO")

    class Meta:
        verbose_name = _("Home SEO")
        verbose_name_plural = _("Home SEO")


class BannerSlide(TranslatableModel):
    translations = TranslatedFields(
        maintitle=models.CharField(
            _("Main Title"), blank=True, null=True, max_length=200
        ),
        subtitle=models.CharField(_("Subtitle"), blank=True, null=True, max_length=200),
        description=models.TextField(_("Description"), null=True, blank=True),
        redirect_link=models.CharField(
            _("Redirect Link"),
            blank=True,
            null=True,
            max_length=300,
            help_text="You can enter full url or relative path like '/about'",
        ),
    )
    image = models.ImageField(_("Image"), upload_to="banner/slides")
    order = models.IntegerField(_("Order"), default=0)

    def __str__(self):
        return _("Banner Slider %s") % self.id

    class Meta:
        verbose_name = _("Banner Slider")
        verbose_name_plural = _("Banner Sliders")
        ordering = ("order",)

page/models/journey.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext as _tr
from django.utils.translation import ugettext_lazy as _
from parler.models import TranslatableModel, TranslatedFields
from parler.utils.context import switch_language

from page.models import seo_translations, SEOStarterModel
from utils.models import BannerStarterModel


class JourneyPageSeo(TranslatableModel, SEOStarterModel, BannerStarterModel):
    translations = TranslatedFields(
        **BannerStarterModel.translations,
        **seo_translations,
    )

    class Meta:
        verbose_name = _("Journey Page SEO")
        verbose_name_plural = _("Journey Page SEO")

    def __str__(self):
        return _tr("Journey Page SEO")


class JourneyItem(TranslatableModel):
    translations = TranslatedFields(
        title=models.CharField(_("Title"), max_length=100),
        slug=models.SlugField(_("Slug"), max_length=100),
        content=RichTextUploadingField(_("Content"), blank=True, null=True),
        description=models.TextField(_("Description"), blank=True, null=True),
    )
    image = models.ImageField(
        _("Image"), upload_to="journey", blank=True, null=True
    )

    class Meta:
        verbose_name = _("Journey Item")
        verbose_name_plural = _("Journey Items")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        with switch_language(self):
            path = reverse("journey")
            return f"{path}?item={self.slug}"

page/models/pricing.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import ugettext as _tr
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField
from parler.models import TranslatableModel, TranslatedFields
from page.models import seo_translations, SEOStarterModel
from utils.models import BannerStarterModel


class PricingPlan(TranslatableModel, SEOStarterModel, BannerStarterModel):
    translations = TranslatedFields(
        name=models.CharField(_("Name"), max_length=100),
        page_title=models.CharField(
            _("Page Title"), max_length=200, blank=True, null=True
        ),
        content=RichTextUploadingField(_("Page Content"), blank=True, null=True),
        **BannerStarterModel.translations,
        **seo_translations,
    )
    order = models.IntegerField(_("Ordering"), default=0)
    is_special = models.BooleanField(_("Is Special?"), default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Pricing Plan")
        verbose_name_plural = _("Pricing Plans")
        ordering = ("order",)

    def get_absolute_url(self):
        # Pricing plan URLs removed from site
        return "#"


class PricingPlanFeature(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(_("Name"), max_length=100),
    )
    plan = models.ForeignKey(
        PricingPlan,
        on_delete=models.CASCADE,
        verbose_name=_("Pricing Plan"),
        related_name="features",
    )
    is_checked = models.BooleanField(_("Is Checked?"), default=True)
    order = models.IntegerField(_("Ordering"), default=0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Pricing Plan Feature")
        verbose_name_plural = _("Pricing Plan Features")
        ordering = ("order",)


class PricesPageSeo(TranslatableModel, SEOStarterModel, BannerStarterModel):
    translations = TranslatedFields(
        title=models.CharField(_("Page Title"), max_length=200, blank=True, null=True),
        content=RichTextUploadingField(_("Content"), blank=True, null=True),
        **BannerStarterModel.translations,
        **seo_translations,
    )

    class Meta:
        verbose_name = _("Prices Page SEO")
        verbose_name_plural = _("Prices Page SEO")

    def __str__(self):
        return _tr("Prices Page SEO")


class PriceServiceCategory(TranslatableModel):
    translations = TranslatedFields(
        title=models.CharField(_("Title"), max_length=100),
        slug=models.SlugField(_("Slug"), max_length=100),
        description=models.TextField(_("Description"), blank=True, null=True),
    )
    order = models.IntegerField(_("Ordering"), default=0)

    class Meta:
        verbose_name = _("Price Service Category")
        verbose_name_plural = _("Price Service Categories")
        ordering = ("order",)

    def __str__(self):
        return self.title


class PriceServiceItem(TranslatableModel):
    translations = TranslatedFields(
        title=models.CharField(_("Title"), max_length=200, blank=True, null=True),
        content=RichTextUploadingField(_("Content"), blank=True, null=True),
    )
    page = models.ForeignKey(PricesPageSeo, on_delete=models.CASCADE)
    category = models.ForeignKey(
        PriceServiceCategory,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    price = models.CharField(_("Price"), max_length=50)
    order = models.IntegerField(_("Ordering"), default=0)

    class Meta:
        verbose_name = _("Price Service Item")
        verbose_name_plural = _("Price Service Items")
        ordering = ("order",)

    def __str__(self):
        return self.title

templates/page/blog-details.html
{% extends "base.html" %}
{% load i18n %}
{% load blogs %}

{% block meta %}
    {% include "components/base/meta.html" with obj=blog %}
{% endblock %}

{% block banner %}
    {% include "components/banner.html" with obj=blog %}
{% endblock %}


{% block content %}
    <section class="postbox__area pt-100 pb-100">
        <div class="container">
            <div class="row">
                <div class="col-xxl-8 col-xl-8 col-lg-8">
                    <div class="postbox__wrapper">
                        <article class="postbox__item format-image mb-50 transition-3">
                            {% if blog.image %}
                                <div class="postbox__thumb w-img mb-25">
                                    <a href="{{ blog.get_absolute_url }}">
                                        <img src="{{ blog.image.url }}" alt="img">
                                    </a>
                                </div>
                            {% endif %}
                            <div class="postbox__content mr-70">
                                <div class="postbox__meta mb-20">
                                    <a href="{{ blog.category.get_absolute_url }}">
                                        <span>
                                            <i class="fa-regular fa-location-dot"></i> {{ blog.category.title }}
                                        </span>
                                    </a>
                                </div>
                                <h3 class="postbox__title mb-10">
                                    {{ blog.title }}
                                </h3>
                                <div class="postbox__text pb-10">
                                    {{ blog.content|safe|default_if_none:"" }}
                                </div>
                            </div>
                        </article>

                        {% include 'components/forms/first-step-form.html' %}
                    </div>
                </div>
                <div class="col-xxl-4 col-xl-4 col-lg-4">
                    <div class="sidebar__wrapper">
                        {% include 'components/blog/search-widget.html' %}

                        {% include 'components/blog/blog-categories.html' %}

                        {% include 'components/blog/recent-items.html' %}

                    </div>
                </div>
            </div>
            {% include "components/faqs.html" with faqs=blog.faq_set.all obj=blog %}
        </div>
    </section>

{% endblock %}

templates/page/blogs.html
{% extends "base.html" %}
{% load i18n %}
{% load blogs %}

{% block meta %}
    {% get_blogs_seo_obj as obj %}
    {% include "components/base/meta.html" %}
{% endblock %}

{% block banner %}
    {% get_blogs_seo_obj as obj %}
    {% include "components/banner.html" %}
{% endblock %}


{% block content %}
    <!-- postbox area start -->
    <section class="postbox__area pt-120 pb-120">
        <div class="container">
            <div class="row">
                <div class="col-xxl-8 col-xl-8 col-lg-8">
                    <div class="postbox__wrapper">
                        {% for blog in blog_list %}
                            {% include 'components/blog/blog-item.html' %}
                        {% endfor %}
                        {% include 'components/pagination.html' %}
                    </div>
                </div>
                <div class="col-xxl-4 col-xl-4 col-lg-4">
                    <div class="sidebar__wrapper">
                        {% include 'components/blog/search-widget.html' %}

                        {% include 'components/blog/blog-categories.html' %}

                        {% include 'components/blog/recent-items.html' %}


                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- postbox area end -->

{% endblock %}

templates/page/contact.html
{% extends "base.html" %}
{% load i18n %}
{% load contact %}

{% block meta %}
{% get_contact_seo_obj as obj %}
{% include "components/base/meta.html" %}
{% endblock %}

{% block banner %}
{% get_contact_seo_obj as obj %}
{% include "components/banner.html" %}
{% endblock %}


{% block content %}
<!-- contact info area start -->
<section class="rr-contact-area pt-100 pb-100">
    <div class="container">
        <div class="row">
            <div class="col-xl-4 col-lg-4 col-md-4 wow rrfadeUp" data-wow-duration=".9s" data-wow-delay=".3s">
                <a href="tel:{{ global_preferences.page__phone_number|cut:' ' }}">
                    <div class="rr-contat-box-info">
                        <div class="rr-contact-box-item d-flex align-items-center p-relative">
                            <div class="rr-contact-box-icon mr-20">
                                <span><i class="fa-solid fa-phone"></i></span>
                            </div>
                            <div class="rr-contact-box-contat">
                                <span>{% translate 'Call Now' %}</span>
                                <p>
                                    {{ global_preferences.page__phone_number }}
                                </p>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-xl-4 col-lg-4 col-md-4 wow rrfadeUp" data-wow-duration=".9s" data-wow-delay=".5s">
                <a href="{{ global_preferences.page__address_map_link }}">
                    <div class="rr-contat-box-info">
                        <div class="rr-contact-box-item d-flex align-items-center p-relative">
                            <div class="rr-contact-box-icon mr-20">
                                <span><i class="fa-solid fa-location-dot"></i></span>
                            </div>
                            <div class="rr-contact-box-contat">
                                <span>{% translate 'Address' %}</span>
                                <p>
                                    {{ global_preferences.page__address }}
                                </p>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-xl-4 col-lg-4 col-md-4 wow rrfadeUp" data-wow-duration=".9s" data-wow-delay=".7s">
                <a href="mailto:{{ global_preferences.page__email_address }}">
                    <div class="rr-contat-box-info">
                        <div class="rr-contact-box-item d-flex align-items-center p-relative">
                            <div class="rr-contact-box-icon mr-20">
                                <span><i class="fa-sharp fa-solid fa-envelope"></i></span>
                            </div>
                            <div class="rr-contact-box-contat">
                                <span>{% translate 'Email Us' %}</span>
                                <p>
                                    {{ global_preferences.page__email_address }}
                                </p>
                            </div>
                        </div>
                    </div>
                </a>
            </div>

        </div>
    </div>
</section>
<!-- contact info area end -->

{% include 'components/about/contact_area.html' with apply_negative_margin=True %}

{% endblock %}

templates/page/gdpr.html
{% extends "base.html" %}
{% load i18n %}
{% load gdpr_page %}

{% block meta %}
    {% get_gdpr_obj as obj %}
    {% include "components/base/meta.html" %}
{% endblock %}

{% block banner %}
    {% get_gdpr_obj as obj %}
    {% include "components/banner.html" %}
{% endblock %}


{% block content %}
    {% get_gdpr_obj as obj %}
    <section class="postbox__area pt-100 pb-100">
        <div class="container">
            <h4 class="rr-section-title pb-5">{% translate "GDPR" %}</h4>
            {{ obj.content|safe|default_if_none:"" }}
        </div>
    </section>

{% endblock %}

templates/page/home.html
{% extends "base.html" %}
{% load static i18n %}
{% load home_page %}

{% block meta %}
    {% get_home_obj as obj %}
    {% include "components/base/meta.html" %}
{% endblock %}


{% block content %}

    {% include 'components/home/slider.html' %}

    {% include 'components/home/about.html' %}

    {% include 'components/home/ivf-services.html' %}

    {% include 'components/home/ivf-journey.html' %}

    {% include "components/about/how_it_works_content.html" %}

    {% include 'components/home/patient-comments.html' %}

    {% include 'components/home/pricing.html' %}
    
    {% include 'components/home/blog.html' %}

{% endblock %}

templates/page/pricing-plan.html
{% extends "base.html" %}
{% load i18n %}

{% block meta %}
{% include "components/base/meta.html" with obj=plan %}
{% endblock %}

{% block banner %}
{% include "components/banner.html" with obj=plan %}
{% endblock %}


{% block content %}
<section class="postbox__area pt-100 pb-100">
    <div class="container">
        <h4 class="rr-section-title pb-5">{{plan.page_title|default_if_none:plan.name}}</h4>
        {{ plan.content|default_if_none:""|safe }}
    </div>
</section>

{% endblock %}

templates/page/pricing.html
{% extends "base.html" %}
{% load i18n %}
{% load pricing %}

{% block meta %}
{% get_prices_page_obj as obj %}
{% include "components/base/meta.html" %}
{% endblock %}

{% block banner %}
{% get_prices_page_obj as obj %}
{% include "components/banner.html" %}
{% endblock %}


{% block content %}
{% get_prices_page_obj as obj %}
<section class="postbox__area pt-100 pb-50">
    <div class="container">
        <h4 class="rr-section-title pb-5">{{obj.title|default_if_none:""}}</h4>
        {{ obj.content|safe|default_if_none:"" }}
    </div>
</section>


<section class="postbox__area pt-50 pb-100">
    <div class="container">
        <h4 class="rr-section-title pb-5">{% translate "" %}</h4>

        <table class="table table-bordered">
            {% get_prices_categories as price_categories %}
            {% for price_category in price_categories %}
            <tr class="table-primary">
                <th colspan="2">{{price_category.title}}</th>
            </tr>
            {% if price_category.description %}
            <tr>
                <td colspan="2">
                    {{price_category.description}}
                </td>
            </tr>
            {% endif %}
            {% for price_item in price_category.priceserviceitem_set.all %}
            <tr>
                <td>
                    {% if price_item.content %}
                    <div class="accordion accordion-pricing" id="accordion-{{price_item.pk}}">
                        <div class="accordion-item border-0">
                            <h2 class="accordion-header">
                                <button class="accordion-button collapsed " type="button" data-bs-toggle="collapse"
                                    data-bs-target="#collapse-{{price_item.pk}}" aria-expanded="true"
                                    aria-controls="collapse-{{price_item.pk}}">
                                    {{price_item.title}}
                                    <i class="bi bi-chevron-down ms-auto"></i>
                                </button>
                            </h2>
                            <div id="collapse-{{price_item.pk}}" class="accordion-collapse collapse"
                                data-bs-parent="#accordion-{{price_item.pk}}">
                                <div class="accordion-body">
                                    {{price_item.content|safe}}
                                </div>
                            </div>
                        </div>
                    </div>
                    {% else %}
                    <div class="px-4 py-2">
                        {{price_item.title}}
                    </div>
                    {% endif %}
                </td>
                <td class="col-2 px-4 align-middle text-center">
                    {{price_item.price}}
                </td>
            </tr>
            {% endfor %}
        {% endfor %}

        </table>
    </div>
</section>

{% endblock %}

templates/page/privacy.html
{% extends "base.html" %}
{% load i18n %}
{% load gdpr_page %}

{% block meta %}
    {% get_privacy_obj as obj %}
    {% include "components/base/meta.html" %}
{% endblock %}

{% block banner %}
    {% get_privacy_obj as obj %}
    {% include "components/banner.html" %}
{% endblock %}


{% block content %}
    {% get_privacy_obj as obj %}
    <section class="postbox__area pt-100 pb-100">
        <div class="container">
            <h4 class="rr-section-title pb-5">{% translate "Privacy" %}</h4>
            {{ obj.content|safe|default_if_none:"" }}
        </div>
    </section>

{% endblock %}

templates/page/service-detail.html
{% extends "base.html" %}

{% block meta %}
    {% include "components/base/meta.html" with obj=service %}
{% endblock %}

{% block banner %}
    {% include "components/banner.html" with obj=service %}
{% endblock %}

{% block content %}

    <!-- service details area start -->
    <section class="rr-services-details-area pt-100 pb-80">
        <div class="container">
            <div class="row mb-40">
                <div class="col-12 col-md-8">
                    {% if service.image %}
                        <div class="mb-50">
                            <div class="rr-services-details-thumb">
                                <img src="{{ service.image.url }}" alt="img">
                            </div>
                        </div>
                    {% endif %}
                    <div class="rr-service-details-info mt-20">
                        <h4>{{ service.title }}</h4>
                        {{ service.content|safe|default_if_none:"" }}
                    </div>
                    {% include "components/faqs.html" with faqs=service.faq_set.all obj=service %}
                    {% include 'components/forms/first-step-form.html' %}
                </div>
                <div class="col-12 col-md-4">
                    {% include 'components/services/service-categories.html' %}
                    
                    {% include 'components/services/patient-comments.html' %}

                </div>
            </div>
                </div>
    </section>

    {% include 'components/home/pricing.html' with apply_negative_margin=True %}
{% endblock %}